import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import { Container } from 'react-bootstrap'
import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css';
import 'remixicon/fonts/remixicon.css'
export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Container className='py-4'>
      <Component {...pageProps} />
    </Container>
    
    </>
  )
}
